/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package okienka;

import java.awt.Color;
import okienka.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import kinomaniak_objs.Attraction;
import kinomaniak_objs.Product;
import kinomaniak_objs.Show;
import kinomaniak_z_interfejsem.KinomaniakKlientMoj2;
import kinomaniak_z_interfejsem.KinomaniakKlientMoj2;

/**
 *
 * @author Adam
 */
public class OknoAtrakcji extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form OknoSeansow
     */
    public OknoAtrakcji() {
        initComponents();
    }
    private Attraction[] atrakcje = new Attraction[30];
    private JButton[] button = new JButton[30];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Okno wyboru atrakcji");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Powrót");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(523, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(566, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void wyczyscOkno(){
  //     for(int i=0;i<=9;i++){
//                 KinomaniakKlientMoj2.klient2.oknseans.remove(button[i]);
            }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        KinomaniakKlientMoj2.klient2.oknatrakcji.setVisible(false);
        KinomaniakKlientMoj2.klient2.okngl.setVisible(true);
        KinomaniakKlientMoj2.klient2.oknatrakcji.repaint();
        this.wyczyscOkno();
    }//GEN-LAST:event_jButton1ActionPerformed

    void rysujPrzyciski() {
        int x=30,y=50;
        KinomaniakKlientMoj2.klient2.pobierzAtrakcje();
        atrakcje = KinomaniakKlientMoj2.klient2.getAtrakcje();
        for (int i=0;i<atrakcje.length;i++){
                    button[i] = new JButton();          
                    button[i].setSize(180,100); 
                   //System.out.println(shss[i].getMovie().getName()+"-"+shss[i].getFormattedDate()
                     //       +"sala: "+shss[i].getRoom().getID()+"showID:"+shss[i].getID());
                    button[i].setName(""+atrakcje[i].getId());
                    button[i].setText("<html>"+atrakcje[i].getName()+"<br />"+"Cena: "+atrakcje[i].getPrice()
                            +"zł"+"<br />");
                    if (y>500){
                        y=50;
                        x+=180;
                    }
                    button[i].setLocation(x,y);
                    y+=100;
                    button[i].revalidate();
                    KinomaniakKlientMoj2.klient2.oknatrakcji.add(button[i]);
                    button[i].addActionListener(this);
                    KinomaniakKlientMoj2.klient2.oknatrakcji.revalidate();
                    KinomaniakKlientMoj2.klient2.oknatrakcji.repaint();
    }}
    private void usunBatony(){
//        for (int i=0;i<button.length;i++)
//            button[i]=null;
//        for (int i=0;i<produkty.length;i++)
//            produkty[i]=null;
//        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoSeansow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoSeansow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoSeansow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoSeansow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoSeansow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        this.rysujPrzyciski();
        JButton zrodlo = (JButton) ae.getSource();
//        System.out.println((String)zrodlo.get)
         System.out.println((String)zrodlo.getName());
         //KinomaniakKlientMoj2.klient2.sprzedajAtrakcje(atrakcje[Integer.parseInt(zrodlo.getName())]);
         for (int i=0;i<atrakcje.length;i++)
             if(Integer.parseInt(zrodlo.getName())==atrakcje[i].getId()){
                 KinomaniakKlientMoj2.klient2.sprzedajAtrakcje(atrakcje[i]);
                 KinomaniakKlientMoj2.klient2.okngl.dodajDoKoszyka(atrakcje[i].getName(),atrakcje[i].getPrice());}
         KinomaniakKlientMoj2.klient2.oknatrakcji.repaint();
      //   this.usunBatony();
         KinomaniakKlientMoj2.klient2.oknatrakcji.setVisible(false);
         KinomaniakKlientMoj2.klient2.okngl.setVisible(true);
         
         
        

        //To change body of generated methods, choose Tools | Templates.
    }
}