/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package okienka;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import kinomaniak_objs.Product;
import kinomaniak_objs.Show;
import kinomaniak_z_interfejsem.KinomaniakKlientMoj2;

/**
 *
 * @author Adam
 */
public class OknoProduktow extends javax.swing.JFrame {

    /**
     * Creates new form OknoProduktow
     */
    public OknoProduktow() {
        initComponents();
    }
private JButton[] button = new JButton[30];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void rysujPrzyciski() {
        int x=50,y=50;int i1=1;int i2=1;int i3=1;
        KinomaniakKlientMoj2.klient2.pobierzProdukty();
        Product[] produkty = KinomaniakKlientMoj2.klient2.getProdukt();
        for (int i=0;i<=produkty.length-1;i++){
                    button[i] = new JButton();          
                    button[i].setSize(150,150); 
                //  System.out.println(shss[i].getMovie().getName()+"-"+shss[i].getFormattedDate()
                 //           +"sala: "+shss[i].getRoom().getID()+"showID:"+shss[i].getID());
                   button[i].setName(""+produkty[i].getId());
                    button[i].setText("<html>"+produkty[i].getName()+"<br />"+produkty[i].getPrice()+"</html>");
                    button[i].setLocation(30,i*150);
                    KinomaniakKlientMoj2.klient2.oknprodukt.add(button[i]);
                    button[i].addActionListener((ActionListener) this);
                    KinomaniakKlientMoj2.klient2.oknprodukt.repaint();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoProduktow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoProduktow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoProduktow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoProduktow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoProduktow().setVisible(true);
            }
        });
    }
    public void actionPerformed(ActionEvent ae) {
        JButton zrodlo = (JButton) ae.getSource();
//        System.out.println((String)zrodlo.get)
         System.out.println((String)zrodlo.getName());
         int tmp = Integer.parseInt(zrodlo.getName());
         KinomaniakKlientMoj2.klient2.oknsali.setVisible(true);
         KinomaniakKlientMoj2.klient2.oknseans.setVisible(false);
         KinomaniakKlientMoj2.klient2.oknsali.rysujSale(tmp);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
